theme = "catppuccin_macchiato"

[editor]
mouse = false
# Show currently open buffers, only when more than one exists.
bufferline = "multiple"
# Highlight all lines with a cursor
cursorline = true
# Use relative line numbers
line-number = "relative"
# Show a ruler at column 120
#onf:rulers = [120]
# Force the theme to show colors
true-color = true

[editor.indent-guides]
character = "╎"
render = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name"]
